{% set name = "cgns" %}
{% set version = "3.3.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/{{ name.upper() }}/{{ name.upper() }}
  git_rev: v{{ version }}
  patches:
    - interface.patch

build:
  number: 0

requirements:
  build:
    - cmake=2.8
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - zlib
    - hdf5
  run:
    - zlib
    - hdf5

test:
  commands:
    - cgnscheck

about:
  home: http://cgns.org
  license: Public domain
  summary:
    The CFD General Notation System (CGNS) provides a standard for
    recording and recovering computer data associated with the
    numerical solution of fluid dynamics equations.
  dev_url: https://github.com/CGNS/CGNS
